### PR TITLE
Incidents: NASA report on the Toyota Unintended Acceleration Issue

### PR DESCRIPTION
**Pull request by stanislaw**

### CODE REVIEW

**Comment by dodikk** [comment]
@stanislaw , most likely, I'm posting some off-topic, but I just couldn't help sharing this with you.

Here are few articles about Toyota with interesting (imho) insights and thoughts.

* http://ko.com.ua/kachestvo_vstraivaemogo_po_ili_pogrom_vsyo-taki_sluchilsya_98518
* http://ko.com.ua/slozhnoe_i_tolko_li_dlya_programmistov_prodolzhenie_istorii_s_firmware_toyota_i_para_slov_o_poleznom_v_bytu_101816
* http://ko.com.ua/prodolzhenie_istorii_s_toyota_i_nechto_ochen_ochevidnoe_o_nachale_istorii_iot_107266


P.S. Their author is a Ukrainian journalist (with a solid background in tech and embedded topics), so the articles are in russian.
P.P.S. They might contain some non-related materials due to the journal's issue format.

**Comment by stanislaw** [comment]
@dodikk thanks for sharing.

I am still not set up with my thoughts about the rules we should use to introduce new content. I have also found a bunch of interesting articles about this issue however currently I am rather trying to only add actual papers or reports from the "first-party" people.

**Comment by dodikk** [comment]
Actually, I wasn't suggesting to add those links (otherwise I whould have sent a pull request).
Just wanted you to take a look.

By the way, I really enjoy the theory on "why there are 11K globals in the firmware" in the article [2]
(from my comment above)

**Comment by dodikk** [comment]
>> I have also found a bunch of interesting articles about this issue

Could you share some of those as a comment in this thread, please?

**Comment by stanislaw** [comment]
@dodikk 

I need some time to process your links from `ko.com.ua` but overall I think it is a good idea to introduce a Russian version of this list in a separate file `README.RU.md`. I will do this soon.

> Could you share some of those as a comment in this thread, please?

No I lost the link by this point.

**Pull request merged**
